export const LEGACY_EXTENSION_ID = 'iarjian.leek-fund';

export const LEGACY_COMMAND_ALIASES: ReadonlyArray<readonly [string, string]> = [
  ['leek-fund.refreshStock', 'stock-fund.refreshStock'],
  ['leek-fund.refreshFund', 'stock-fund.refreshFund'],
  ['leek-fund.sortStock', 'stock-fund.sortStock'],
  ['leek-fund.sortFund', 'stock-fund.sortFund'],
  ['leek-fund.sortAmountFund', 'stock-fund.sortFundAmount'],
  ['leek-fund.refreshBinance', 'stock-fund.refreshBinance'],
  ['leek-fund.binanceSort', 'stock-fund.sortBinance'],
  ['leek-fund.refreshForex', 'stock-fund.refreshForex'],
  ['leek-fund.toggleFlashNews', 'stock-fund.toggleNewsOutput'],
  ['leek-fund.leekCenterView', 'stock-fund.openLeekCenter'],
  ['leek-fund.viewFundRank', 'stock-fund.viewFundRanking'],
  ['leek-fund.viewFundTrend', 'stock-fund.viewFundOverview'],
  ['leek-fund.viewFundPosition', 'stock-fund.viewFundDetails'],
  ['leek-fund.viewStockDetails', 'stock-fund.viewStockDetails'],
  ['leek-fund.viewStockPosition', 'stock-fund.viewStockDetails'],
  ['leek-fund.viewFundFlow', 'stock-fund.viewFundFlows'],
  ['leek-fund.viewMainFundFlow', 'stock-fund.openMainCapitalFlow'],
  ['leek-fund.stockWindVane', 'stock-fund.viewMarketSentiment'],
  ['leek-fund.openAiConfig', 'stock-fund.configureAi'],
  ['leek-fund.setAiStockHistoryRange', 'stock-fund.configureAiHistoryRange'],
  ['leek-fund.customSetting', 'stock-fund.openPersonalization'],
  ['leek-fund.exportSettings', 'stock-fund.exportSettings'],
  ['leek-fund.importSettings', 'stock-fund.importSettings'],
  ['leek-fund.toggleKLineChartSwitch', 'stock-fund.toggleStockChartMode'],
  ['leek-fund.toggleStockHeldTipShow', 'stock-fund.toggleHeldStockHighlight'],
  ['leek-fund.toggleRemindSwitch', 'stock-fund.toggleReminders'],
  ['leek-fund.toggleStatusBarVisibility', 'stock-fund.toggleAllStatusBars'],
  ['leek-fund.toggleStatusBarIconVisibility', 'stock-fund.toggleStatusBarIcons'],
  ['leek-fund.toggleFundBarVisibility', 'stock-fund.toggleFundPortfolioStatusBar'],
  ['leek-fund.toggleStockBarVisibility', 'stock-fund.toggleMarketStatusBar'],
];
