export const LEGACY_EXTENSION_ID = 'iarjian.leek-fund';

export const LEGACY_COMMAND_ALIASES: ReadonlyArray<readonly [string, string]> = [
  ['leek-fund.refreshStock', 'tickerdock.refreshStock'],
  ['leek-fund.refreshFund', 'tickerdock.refreshFund'],
  ['leek-fund.sortStock', 'tickerdock.sortStock'],
  ['leek-fund.sortFund', 'tickerdock.sortFund'],
  ['leek-fund.sortAmountFund', 'tickerdock.sortFundAmount'],
  ['leek-fund.refreshBinance', 'tickerdock.refreshBinance'],
  ['leek-fund.binanceSort', 'tickerdock.sortBinance'],
  ['leek-fund.refreshForex', 'tickerdock.refreshForex'],
  ['leek-fund.toggleFlashNews', 'tickerdock.toggleNewsOutput'],
  ['leek-fund.leekCenterView', 'tickerdock.openLeekCenter'],
  ['leek-fund.viewFundRank', 'tickerdock.viewFundRanking'],
  ['leek-fund.viewFundTrend', 'tickerdock.viewFundOverview'],
  ['leek-fund.viewFundPosition', 'tickerdock.viewFundDetails'],
  ['leek-fund.viewStockDetails', 'tickerdock.viewStockDetails'],
  ['leek-fund.viewStockPosition', 'tickerdock.viewStockDetails'],
  ['leek-fund.viewFundFlow', 'tickerdock.viewFundFlows'],
  ['leek-fund.viewMainFundFlow', 'tickerdock.openMainCapitalFlow'],
  ['leek-fund.stockWindVane', 'tickerdock.viewMarketSentiment'],
  ['leek-fund.openAiConfig', 'tickerdock.configureAi'],
  ['leek-fund.setAiStockHistoryRange', 'tickerdock.configureAiHistoryRange'],
  ['leek-fund.customSetting', 'tickerdock.openPersonalization'],
  ['leek-fund.exportSettings', 'tickerdock.exportSettings'],
  ['leek-fund.importSettings', 'tickerdock.importSettings'],
  ['leek-fund.toggleKLineChartSwitch', 'tickerdock.toggleStockChartMode'],
  ['leek-fund.toggleStockHeldTipShow', 'tickerdock.toggleHeldStockHighlight'],
  ['leek-fund.toggleRemindSwitch', 'tickerdock.toggleReminders'],
  ['leek-fund.toggleStatusBarVisibility', 'tickerdock.toggleAllStatusBars'],
  ['leek-fund.toggleStatusBarIconVisibility', 'tickerdock.toggleStatusBarIcons'],
  ['leek-fund.toggleFundBarVisibility', 'tickerdock.toggleFundPortfolioStatusBar'],
  ['leek-fund.toggleStockBarVisibility', 'tickerdock.toggleMarketStatusBar'],
];
